spring:
    datasource:
      url: jdbc:sqlserver://localhost:1433;database=playSpring
      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
      username: playSpring
      password: playSpring