spring:
    profiles:
      active: local,hsql
    data:   
      jpa:
        repositories:
          enable: true
        hibernate.ddl-auto: update
        show-sql: true
        properties:
          hibernate:
            format_sql: false
            use_sql_comments: true