spring:
    profiles:
      active: local
    datasource:
      #url: jdbc:sqlserver://localhost:1433;
      url: jdbc:mysql://localhost:3400/playSpring?autoReconnect=true&useSSL=false
      driver-class-name: com.mysql.jdbc.Driver
      username: playSpring
      password: playSpring